version: '3'
services:
  app:
    container_name: customer_ticketing
    restart: always
    build: .
    env_file: .env
    environment:
      DATABASE_URL: 'mongodb://$DB_USER:$DB_PASSWORD@mongodb:27017'
      DATABASE_NAME: $DATABASE_NAME
      APP_PORT: $APP_PORT
    ports:
      - '6000:6000'
    depends_on:
      - redis
      - mongodb
      - mongo-express
  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
  mongodb:
    container_name: mongo-dev
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo-dev
    depends_on:
      - mongodb
