version: 2.1

jobs:
  build-and-test:
    docker:
      - name: circle/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - node/with-cache:
          steps:
            - run: docker build . -t $CIRCLE_SHA_SHORT
            - run: docker run $CIRCLE_SHA_SHORT
workflows:
  build-and-test:
    jobs:
      - build-and-test
