version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      - node/with-cache:
          steps:
            - run: docker build . -t $CIRCLE_SHA_SHORT
            - run: docker run $CIRCLE_SHA_SHORT
workflows:
  build-and-test:
    jobs:
      - build-and-test
