version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circle/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
        keys:
            - v1-pkg-cache

     - run: docker build . -t $CIRCLE_SHA_SHORT
     - run: docker run $CIRCLE_SHA_SHORT
workflows:
  build-and-test:
    jobs:
      - build-and-test
